### ISSUE TITLE
memoize all functions with `mem.all`

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/mem#1]
Something like `pify.all` but to memoize all functions in an object. 

#### example

```js
const memoize = require('mem');
const got = require('got');

const memGot = mem.all(got);

memGot.get('...').then(data => {

});
```

I could do a PR if you like the idea. First want to discuss this :).

**Comment by SamVerschueren** [comment]
`got` might not be a good idea though. You don't want to memoize post, put, delete, ...

So might reconsider the idea.

**Comment by sindresorhus** [comment]
Do you have an actual need? It made sense with `pify` as you usually want to promisify everything, but with `mem` it's usually just one method, not many.

**Comment by SamVerschueren** [comment]
When I thought of it, I had `got` in mind. But I don't think that's a good idea :). So actually, at the moment I don't have the need for it. So if you want, you can close it.

**Comment by sindresorhus** [comment]
We can reconsider when there's an actual need.
