### ISSUE TITLE
Use Keyv

### ISSUE THREAD

**Issue by lukechilds** [sindresorhus/mem#15]
Are you interested in backing this with Keyv?

https://github.com/lukechilds/keyv

It would work in memory like it does currently but give users the option to use a persistent store like Redis/Mongo/Postgres/etc and share memoized results between servers/restarts.

It would also solve the memory leak issue in https://github.com/sindresorhus/mem/issues/14 via Keyv's built in TTL support.

**Comment by SamVerschueren** [comment]
I believe it should be done in a different package as it would make the entire API async and solves a different use case imo.

**Comment by lukechilds** [comment]
Ah, good point regarding async, hadn't considered that.

**Comment by sindresorhus** [comment]
Could maybe be added to https://github.com/sindresorhus/p-memoize instead, since it only supports promises.

**Comment by Kikobeats** [comment]
@lukechilds I'm trying to use `keyv` with `mem` (using async functions) but `mem` needs to use `cache.has` that is missing at `keyv` interface.

could be possible extend `keyv` to add a `.has` that basically should be based on `.get`?
