### ISSUE TITLE
Get wrong results when use regexp or Symbol as function arguments

### ISSUE THREAD

**Issue by elvinn** [sindresorhus/mem#20]
Because use `JSON.stringify(args)` in `defaultCacheKey` function, it will get wrong results when using regexp or Symbol as function arguments.

The reasons are:

```js
console.log(JSON.stringify(/Sindre Sorhus/));
// => '{}'

console.log(JSON.stringify(/Elvin Peng/));
// => '{}'

console.log(JSON.stringify({foo: Symbol('Sindre Sorhus')}));
// => '{}'

console.log(JSON.stringify({foo: Symbol('Elvin Peng')}));
// =>'{}'
```

**Comment by sindresorhus** [comment]
I'm open to suggestions on how to better handle this. A `Symbol` cannot really be properly stringified as it doesn't have any value. Even if you give two symbols the same description, per definition, they are supposed to be unique, but there's no way (as far as I know) for us to stringify them as unique values. A regex could be handled somehow though, since it can be stringified with `.toString()`. So maybe if instead of JSON.stringifying the whole arguments object, we stringify each item and also include its type and also specially handle regex? That would still not solve the Symbol case.

// @maxwellgerber @keithamus @LinusU

**Comment by LinusU** [comment]
Maybe we could have a WeakMap that maps Symbols into a unique string (e.g. a uuid)?

We could probably make a replacer that we pass to JSON.stringify, so that it would work with RegExps and Symbols inside objects as well.

RegExps could simply be turned into a string with a specific prefix e.g.

```js
if (value instanceof RegExp) {
  return `2fe2df27-4e69-443a-b939-ae259eb929bd:${value}`
}

if (value instanceof Symbol) {
  if (!symbolMap.has(value)) symbolMap.set(value, uuid())
  return symbolMap.get(value)
}

return value
```

**Comment by sindresorhus** [comment]
I like that idea. It would only work if the cache is in memory though. But we can just have a separate cache function for when users want to persist the cache to disk (not a common use-case).

**Comment by elvinn** [comment]
The idea to save Symbol into a WeakMap is GREAT!

**Comment by maxwellgerber** [comment]
We could consider applying this to more than just Symbols - WeakMaps, Sets, Maps, and Sets have a similar problem. 
```
const m = require('mem')
const map = new Map()
map.set('a', 'A')
const memoized = m((map) => map.get('a'))
memoized(map)
const map2 = new Map()
map2.set('a', 'B')
memoized(map2)
```

**Comment by szmarczak** [comment]
Maybe something like:

```js
const kMemoizedId = Symbol('memoizedId');
let globalId = 0;

const defaultCacheKey = (...args) => {
	for (const arg of args) {
		if (!Reflect.has(arg, kMemoizedId)) {
			globalId = (globalId + 1) % 4294967296;
			arg[kMemoizedId] = globalId;
		}
	}

	const ids = args.map(arg => arg[kMemoizedId]).join(',');

	returns `${args.length}:${ids}`;
};
```

**Comment by bfred-it** [comment]
I'd like your thoughts on #33. It would fix this issue once for all, but it requires two changes to how `mem` works.

**Comment by bfred-it** [comment]
I just realized something, order matters:

```js
JSON.stringify({a: 1, b: 1})
// "{\"a\":1,\"b\":1}"

JSON.stringify({b: 1, a: 1})
// "{\"b\":1,\"a\":1}"
```

This means that the cache is hit even less than we realize, I think

**Comment by Kikobeats** [comment]
@bfred-it That's something can easily avoid using a JSON stable stringified, like [`fast-json-stable-stringify`](https://github.com/epoberezkin/fast-json-stable-stringify)
