### ISSUE TITLE
Need to Compile to ES5 before publishing to NPM

### ISSUE THREAD

**Issue by issa-mour** [sindresorhus/mem#23]
if you use create-react-app tool for your react app and you try to build your app for production by "npm run build"  it will fail to minify the code in this file  ./node_modules/mem/index.js

please look on this [link](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) for further information

**Comment by SamVerschueren** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
