### ISSUE TITLE
mem vs. p-memoize

### ISSUE THREAD

**Issue by ghost** [sindresorhus/mem#49]
mem supports promises, and the usage looks identical to p-memoize for the case of promises, which is listed in related packages. If my use-case is promise-only, would you recommend to switch to p-memoize, or should I keep using mem? 

In general it would be nice to clarify the relationship between the two packages in the README.

Thanks!

**Comment by fregante** [comment]
Indeed currently they’re identical or nearly so. You can use `mem` for promises and viceversa. 

I recently opened a PR on `p-memoize` to add support for an asynchronous cache to differentiate the two. This would let you store the memoized values in a database, file system or any other asynchronous storage (via `keyv` package for example)

If you just need a regular `Map` storage you can continue to use `mem` with promises and async functions.

**Comment by fregante** [comment]
@sindresorhus I wonder if it’s worth keeping two packages at all. The only difference will be the cache type (synchronous or asynchronous) and that can probably  detected at runtime by checking whether `.has()` returns a promise instead of a Boolean (or via option)

**Comment by andreasvirkus** [comment]
Does `mem` also support ignoring promise rejections or is that unique to `p-memoize` (configurable via an option)? If they differ in that behaviour, then it seems like a thing worthy of highlighting.

**Comment by sindresorhus** [comment]
@andreasvirkus It's not in the docs, so it does not.
