### ISSUE TITLE
Vulnerability detected : Denial of Service 

### ISSUE THREAD

**Issue by oguilleux** [sindresorhus/mem#53]
Hi, there seems to be a vulnerability :

Denial of Service : https://npmjs.com/advisories/1084 

I'm using gulp-purifycss and here is the path : gulp-purifycss > purify-css > yargs > os-locale > mem

Thanks a ton for your great work !!!

**Comment by fregante** [comment]
> Versions of mem prior to 4.0.0 are vulnerable

The current version is v6. That's an old report

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/mem/issues/14
