### ISSUE TITLE
cacheKey is called with the arguments as an array

### ISSUE THREAD

**Issue by abrenneke** [sindresorhus/mem#54]
The documentation says:

> By default, only the first argument is considered and it only works with primitives. If you need to cache multiple arguments or cache objects by value, use the cacheKey option.

The code shows:

```javascript
const memoized = function (...arguments_) {
    const key = cacheKey(arguments_);

    if (cache.has(key)) {
        return cache.get(key).data;
    }
    ...etc
}
```

In the code, the `cacheKey` function is called with the entire array of arguments, not only the first argument. This happened to be an unlisted breaking change when I upgraded to v5.

I'm assuming that it should be:
```javascript
const memoized = function (...arguments_) {
    const key = cacheKey(...arguments_);

    if (cache.has(key)) {
        return cache.get(key).data;
    }
    ...etc
}
```

But would that be another breaking change?

**Comment by fregante** [comment]
> The code shows:

What code? That's not what the current readme has

**Comment by fregante** [comment]
Sure "the `cacheKey` function is called with the entire array of arguments", but the default `cacheKey` function only uses the first element of that array:

https://github.com/sindresorhus/mem/blob/9d5661e63642c250818306f37af8497eb61e2c11/index.js#L8

**Comment by abrenneke** [comment]
Maybe was just a mistake on my end that the upgrade revealed
