### ISSUE TITLE
Add function decorator

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/mem#60]
When function decorators become stable, we should use them to allow simplifying mem calls:

```js
const mem = require("mem")

@mem.Decorator()
function helloWorld() {
	//...
}
```

**Comment by sindresorhus** [comment]
Would be nice. The decorator proposal has stalled for years though, so this might not happen anytime soon. I don't want to add it until there's support in at least the latest Node.js version.

**Comment by fregante** [comment]
Why not? TypeScript supports them. Worst case scenario, you drop them or replace them in a future breaking release, but until then we can use them.

Currently using a simplified version on https://github.com/fregante/webext-options-sync-per-domain/blob/409d408150b8d7dfdd536204437e3b24f9128872/index.ts#L72

**Comment by sindresorhus** [comment]
Last time I looked into decorators, TS implemented an obsolete version of the spec. That might have changed though. Anyway, I would merge a good PR for this, since there's interest.
