### ISSUE TITLE
Values are memoised across class/prototype instances

### ISSUE THREAD

**Issue by notjosh** [sindresorhus/mem#74]
Hi!

On the surface, it's kind of logical that (by default) values are instances are memoised across instances, because they're just function calls.

However: a) that seems almost never like intended behaviour, and b) there's [a test](https://github.com/sindresorhus/mem/blob/a42d7205cc7939e1738eda2a785fe1ec5bda2760/test.ts#L240-L256) that seems like it's explicitly trying to test for this.

Unfortunately, the test is only correct as a side effect. If you pass a new initial value into the constructor, you can break the logic (I've [fixed the test on my branch](https://github.com/notjosh/mem/commit/65bfb84346e834cfd77d59e89ca2025d479b5b84), but not sure how to fix the actual problem!)

Do you know how, either as a library consumer, or within the library itself we could get this working as expected?

**Comment by fregante** [comment]
Thanks for trying the new decorator and opening an issue. Are you sure that test runs at all? `++this.index` sets it to undefined now I think

**Comment by notjosh** [comment]
The tests run ok, but I think you're referring to not defining `index` on the class? It's using a shorthand syntax for assigning properties directly from the constructor, but is otherwise the same as before. (ref: https://kendaleiv.com/typescript-constructor-assignment-public-and-private-keywords/)

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
Should mem be memoizing values return by a function across instances or for each instance?

**Comment by sindresorhus** [comment]
For each instance by default at least. We could consider adding an option to opt into memorization across instances.
