### ISSUE TITLE
When first call encounter exception, the function always return exception

### ISSUE THREAD

**Issue by zacyang** [sindresorhus/mem#79]
Notice the cache did not distinguish error from regular return, meaning if first try failed, all the subsequent call will fai.
Can we add a configure to allow only cache the success return?

**Comment by fregante** [comment]
The result of functions isn't stored if they throw errors, but **rejected promises** are indeed stored. What you're asking is covered by `p-memoize`, which is a `mem` wrapper

https://github.com/sindresorhus/p-memoize#cachepromiserejection
