### ISSUE TITLE
ERR_REQUIRE_ESM Problem

### ISSUE THREAD

**Issue by v-menzhou** [sindresorhus/mem#85]
Saw this issue  was posted before, https://github.com/sindresorhus/mem/issues/80.  and we are  encouraged to create ES module  by following the link:

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
 

In our case, we  have a utility library X  that is commonjs module. Since  verison 9, mem becomes  ES module, therefore, we change  X to ES module as well. because X is a lib used by many other commonjs projects. We now are in a difficult  position to either to  use mem of version 9 below, or to convert all commonjs projects to ES  projects. 

As for  issue 80,  my understanding  is for those  typescript projects, basically, we can not use  version 9 or after? 

Since mem is a popular utility,  and changing  it to pure ES module  has a huge change impact.  Wonder if  we could  offer distributions of both ES and commonjs module? I do not know how to make this work,   the link below is encouraging:
https://github.com/jhurliman/node-rate-limiter/blob/main/package.json#L10

Thanks for your consideration!

**Comment by sindresorhus** [comment]
I don't have any plans to offer dual package as that is even worse than not: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#gistcomment-3850849
