### ISSUE TITLE
Recommendation for a persistent disk cache

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/mem#86]
Sometimes it's useful to cache certain functions to disk. Especially URL calls for example when testing against 3rd party apis.

Is there an existing implementation of a `CacheStorage` that does this?

Can the default cache be serialized? On first glance it looks like it maps function references, so I would think not...

There would have to be an additional option to allow providing a key for the function, not just the params. But this would require a lot of changes. 

As a workaround, each `mem` call would take a cache specific to its function, and then this could talk to a central disk cache.

I think my specific use case would be simpler without mem, as the abstraction I need is a little bit different.

```typescript
const cachedScraper = cached(scraper)
await cachedScraper()

function cached(fn) {
  return async (...params) => {
    const {name} = fn
    const getter = await fn(params)
    const key = JSON.stringify({name, params})
	if (store[key]) return store[key]
    store[key] = await getter(params)
    writeStore(store)
	return store[key]
  }
}
```

**Comment by sindresorhus** [comment]
Memoization is not meant for persistent caching. It sounds like what you are looking for is a data cache library.

**Comment by vincerubinetti** [comment]
> Memoization is not meant for persistent caching. 

Says who? [This library in python](https://pypi.org/project/diskcache/) has a TTL disk cache with a `@cache.memoize` function decorator. It's a perfectly reasonable request.

Looking into integrating `cacache` with this library at present. Might also just go with https://github.com/borisdiakur/memoize-fs to save time.
