### ISSUE TITLE
Importing error using 'mem' dependency (v9+)

### ISSUE THREAD

**Issue by bitx1** [sindresorhus/mem#87]
**Context**
I generated a Vue 3 app with TypeScript (4.4)/Babel enabled. Running on Node v16.13.0. I am using esm-style (import/export) syntax throughout the project. I have `"type": "module"` set in *package.json* and my typescript configuration (with `"module": "esnext"` set) is include at the bottom for reference.

**Issu?**
Per npm instructions, `import mem from 'mem'` does not work (*dependency was not found* error) but `import mem from 'mem/dist'` does.

Is this expected behavior as part of the move to be ESM-only? I confirmed that having a `main` property within in mem/package.json resolves the issue. Not sure by adding this property goes against the ESM-only spirit but if it does, what is the alternative?

**Reference**
TypeScript config:
```json
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "strict": true,
        "importHelpers": true,
        "moduleResolution": "node",
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        ...
   }
```

**Comment by fregante** [comment]
Refer to https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by fregante** [comment]
I see you updated your post. I think the issue is that something in your pipeline doesn't support the `exports` map in package.json, so you can look into what needs to be changed for that to happen.

**Comment by steven-sheehy** [comment]
I have this same issue after upgrading to node 20. I can workaround by doing `import mem from 'mem/dist'` like above. I also use quick-lru and it doesn't have the same problem. In its [package.json](https://github.com/sindresorhus/quick-lru/blob/6862e8ecab576618c44fe0cb26e9fa921c85a884/package.json#L14) it uses the below. Perhaps mem should be changed similarly and the dist folder dropped?

```javascript
	"exports": {
		"types": "./index.d.ts",
		"default": "./index.js"
	},
```

**Comment by steven-sheehy** [comment]
Nevermind, swapping to https://www.npmjs.com/package/extensionless loader and it works fine. 👍🏻
