### ISSUE TITLE
Enable memoization for prototype methods

### ISSUE THREAD

**Issue by jbenoit2011** [sindresorhus/mem#9]
I managed to use this library with prototype methods by passing `this` instead of `null` in `apply` function at `https://github.com/sindresorhus/mem/blob/master/index.js#L32`.

It allows me to use it like this:

```
function Foo() {
    this.myvalue = 'val';
}
var bar = function () {
    console.log(this.myvalue);
    // Display `val`
};
Foo.prototype.bar = mem(bar)
```
Since I do not know if it is safe, I didn't submit a pull request. Maybe it should be passed through options?

If changing `this` for `null` is ok, I can submit a PR.

**Comment by sindresorhus** [comment]
Sure. PR welcome with a test. I just didn't consider that use-case.
