### ISSUE TITLE
Replace/inline dead `map-age-cleaner` package

### ISSUE THREAD

**Issue by fregante** [sindresorhus/mem#92]
The package is outdated and it has an old [p-defer](https://github.com/sindresorhus/p-defer/releases) dependency:

- https://github.com/SamVerschueren/map-age-cleaner/issues/9
- https://github.com/SamVerschueren/map-age-cleaner/blob/0f9f8631510815dd7f567372461fa923c25f2c46/package.json#L38

Related:

- https://github.com/sindresorhus/mem/pull/91

**Comment by fregante** [comment]
Copy tests and all?

- map-age-cleaner/index.js
- map-age-cleaner/test.js
- map-age-cleaner/license

?

**Comment by sindresorhus** [comment]
Yeah, we can just vendor it for now.
